action.configuration.cacheflush_delete_action:
  type: action_configuration_default
  label: 'Delete cacheflush configuration'

action.configuration.cacheflush_publish_action:
  type: action_configuration_default
  label: 'Publish selected content configuration'

action.configuration.cacheflush_unpublish_action:
  type: action_configuration_default
  label: 'Unpublish selected content configuration'

action.configuration.cacheflush_menu_action:
  type: action_configuration_default
  label: 'Add menu configuration'

action.configuration.cacheflush_nomenu_action:
  type: action_configuration_default
  label: 'Remove menu configuration'
