module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  bg_image_formatter: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  blog: 0
  breakpoint: 0
  bueditor: 0
  ckeditor: 0
  color: 0
  comment: 0
  composer_manager: 0
  config: 0
  config_translation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  entity_clone: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_group_migrate: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  image_raw_formatter: 0
  image_url_formatter: 0
  imce: 0
  kint: 0
  language: 0
  link: 0
  locale: 0
  md_slider: 0
  menu_ui: 0
  naviteam_twig: 0
  node: 0
  nvt_block_settings: 0
  nvt_flickr_feeds: 0
  nvt_menu_attributes: 0
  nvt_views_style: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  path: 0
  php: 0
  quickedit: 0
  rdf: 0
  search: 0
  shortcut: 0
  simplenews: 0
  soundcloudfield: 0
  statistics: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  tweets: 0
  twig_tweak: 0
  uc_attribute: 0
  uc_cart: 0
  uc_country: 0
  uc_order: 0
  uc_product: 0
  uc_report: 0
  uc_store: 0
  unset_html_head_link: 0
  update: 0
  user: 0
  vardumper: 0
  video_embed_field: 0
  views_ui: 0
  votingapi: 0
  votingapi_widgets: 0
  yamlform: 0
  yamlform_devel: 0
  yamlform_node: 0
  yamlform_ui: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  hawell: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: fr
