definitions:
  contact__site_page:
    weight: -48
    menu_name: footer
    parent: ''
    expanded: false
    enabled: true
  standard__front_page:
    weight: -86
    menu_name: main
    parent: ''
    enabled: true
    expanded: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
langcode: fr
