interface:
  default: php_mail
  yamlform: yamlform_php_mail
  uc_cart: ubercart_mail
  uc_order: ubercart_mail
  uc_file: ubercart_mail
  uc_role: ubercart_mail
  uc_stock: ubercart_mail
  uc_store: ubercart_mail
_core:
  default_config_hash: rYgt7uhPafP2ngaN_ZUPFuyI4KdE0zU868zLNSlzKoE
langcode: fr
